version: 2

sources:
  - name: erp
    description: banco replica do erp da northwind
    schema: erp_northwind
    tables:
      - name: orders
        description: uma linha por pedido. inclui pedidos cancelados e deletados.
        columns: 
          - name: order_id
            description: chave primária da tabela de orders
            tests:
            - unique
            - not_null

      - name: products

      - name: order_details

      - name: categories
        description: Tabela com as categorias dos produtos comercializados pela Northwind.
        freshness:
          warn_after:
            count: 24
            period: hour
          warn_after:
            count: 36
            period: hour
        loaded_at_field: el_loaded_raw

      - name: suppliers
        description: Fornecedores dos produtos comercializados pela Northwind.

      - name: employees
        description: Tabela com informações dos funcionários da Northwind e seus gerentes.

      - name: shippers
        description: Transportadoras utilizadas na realização das entregas dos pedidos fechados.

      - name: customers
        description: Tabela com informações dos clientes da Northwind.